## 处理分钟级别的多种交易数据

In [1]:
import pandas as pd
import numpy as np
from tqdm.notebook import tqdm
import matplotlib.pyplot as plt
tqdm.pandas()
# pd.set_option('display.max_rows', 50)

/mnt/datadisk2/aglv/anaconda3/lib/python3.8/site-packages/tqdm/std.py:668: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  from pandas import Panel

In [3]:
data2021 = pd.read_hdf('/mnt/datadisk2/aglv/aglv/lab_aglv/data2021.h5')
data2021

                                Open  Close   High    Low  LastVolume  \
Date     InstrumentID EndTime
20210104 SZ000001     09:31    19.10  18.90  19.10  18.82   3155510.0
                      09:32    18.90  18.80  18.90  18.78   1791334.0
                      09:33    18.80  18.84  18.85  18.81   1656900.0
                      09:34    18.84  18.67  18.82  18.65   2376914.0
                      09:35    18.67  18.57  18.65  18.50   2616000.0
...                              ...    ...    ...    ...         ...
20211231 SH689009     14:56    70.05  70.08  70.18  70.06     13615.0
                      14:57    70.08  70.08  70.08  70.06      7323.0
                      14:58    70.08  70.08  70.08  70.08         0.0
                      14:59    70.08  70.08  70.08  70.08         0.0
                      15:00    70.08  70.07  70.08  70.07     21404.0

                               LastTurnOver
Date     InstrumentID EndTime
20210104 SZ000001     09:31     59855405.18
                      09:32     33745895.32
                      09:33     31190135.00
                      09:34     44535547.45
                      09:35     48631903.70
...                                     ...
20211231 SH689009     14:56       954237.09
                      14:57       513173.86
                      14:58            0.00
                      14:59            0.00
                      15:00      1499778.28

[254119680 rows x 6 columns]

In [4]:
data2021 = data2021.unstack(level='InstrumentID')
data2021.columns.names = ['Type', 'Stock']
data2021

Typr                 Open                                               \
Stock            SH600000 SH600004 SH600006 SH600007 SH600008 SH600009
Date     EndTime
20210104 09:31       9.64    14.10     8.95    12.45     2.86    75.70
         09:32       9.64    14.01     8.82    12.35     2.86    76.46
         09:33       9.60    13.97     8.84    12.36     2.84    76.17
         09:34       9.60    14.00     8.83    12.37     2.85    76.10
         09:35       9.58    13.90     8.83    12.33     2.85    75.74
...                   ...      ...      ...      ...      ...      ...
20211231 14:56       8.55    12.04     6.81    14.41     3.41    46.68
         14:57       8.54    12.03     6.81    14.41     3.40    46.68
         14:58       8.55    12.03     6.81    14.39     3.41    46.70
         14:59       8.55    12.03     6.81    14.39     3.41    46.70
         15:00       8.55    12.03     6.81    14.39     3.41    46.70

Typr                                                  ... LastTurnOver  \
Stock            SH600010 SH600011 SH600012 SH600015  ...     SZ301186
Date     EndTime                                      ...
20210104 09:31       1.17     4.50     6.14     6.22  ...          NaN
         09:32       1.18     4.49     6.12     6.22  ...          NaN
         09:33       1.17     4.47     6.16     6.20  ...          NaN
         09:34       1.17     4.47     6.17     6.21  ...          NaN
         09:35       1.17     4.46     6.16     6.21  ...          NaN
...                   ...      ...      ...      ...  ...          ...
20211231 14:56       2.78     9.64     7.07     5.59  ...     952056.0
         14:57       2.79     9.65     7.07     5.59  ...    2194032.0
         14:58       2.79     9.65     7.06     5.60  ...      17939.0
         14:59       2.79     9.65     7.06     5.60  ...          0.0
         15:00       2.79     9.65     7.06     5.60  ...    3609620.0

Typr                                                                          \
Stock               SZ301188    SZ301189    SZ301190    SZ301193    SZ301198
Date     EndTime
20210104 09:31           NaN         NaN         NaN         NaN         NaN
         09:32           NaN         NaN         NaN         NaN         NaN
         09:33           NaN         NaN         NaN         NaN         NaN
         09:34           NaN         NaN         NaN         NaN         NaN
         09:35           NaN         NaN         NaN         NaN         NaN
...                      ...         ...         ...         ...         ...
20211231 14:56     679846.54  3038382.08  4957085.14   852078.88  1005720.16
         14:57     583407.00  8971445.30  4147009.00   696965.05  1256626.57
         14:58       9840.00   198087.00    15100.00    93226.95        0.00
         14:59          0.00        0.00        0.00        0.00        0.00
         15:00    1340700.00  8639939.02  7305380.00  1127490.00  2231065.29

Typr
Stock               SZ301199     SZ301211    SZ301213     SZ301221
Date     EndTime
20210104 09:31           NaN          NaN         NaN          NaN
         09:32           NaN          NaN         NaN          NaN
         09:33           NaN          NaN         NaN          NaN
         09:34           NaN          NaN         NaN          NaN
         09:35           NaN          NaN         NaN          NaN
...                      ...          ...         ...          ...
20211231 14:56    1060959.00   8443076.96  1982202.45  10979792.45
         14:57    1331142.93  10884780.00  2152394.00   4795641.00
         14:58      66801.00    206917.00     6468.00     95370.00
         14:59          0.00         0.00        0.00         0.00
         15:00    2140845.90  13554644.00  3605550.00   8582753.00

[58320 rows x 27732 columns]