对某一时刻截面中所有股票因子值作为样本空间进行zscore

In [79]:
import pandas as pd
import numpy as np
from scipy.stats import zscore

root = '/mnt/datadisk2/aglv/aglv/lab_aglv/aglv_factor/s_phi_v2_230101_240101_r30.csv'
df = pd.read_csv(root)
df.replace(np.inf, 0, inplace=True)
df.replace(-np.inf, 0, inplace=True)
df = df.iloc[::-1].reset_index(drop=True)
df

,date,SH600718,SZ003816,SZ002656,SH688056,SZ000607,SZ001368,SZ003029,SH600651,SH601339,...,SZ301138,SZ301003,SH600936,SZ002497,SH600509,SH600689,SH688108,SZ002034,SZ000680,SH688132
0,20230103,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20230104,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20230105,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20230106,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20230109,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
237,20231225,0.041509,0.058362,0.200766,-0.009558,-0.261201,0.748428,0.867786,0.257545,-0.214342,...,-0.067675,-0.434309,-0.028454,0.521856,0.911205,0.188146,0.043745,0.029129,0.046179,1.958243
238,20231226,0.015917,0.057803,0.431204,0.040534,-0.243040,0.299958,0.959722,0.281374,-0.197861,...,-0.018152,-0.568761,0.072818,0.526001,0.860078,0.293686,0.018947,0.012601,0.082139,1.304972
239,20231227,0.087823,0.134660,0.168079,0.196840,-0.280552,0.303515,0.583293,0.297228,-0.199477,...,0.119133,-0.446553,0.051750,0.527291,0.658234,0.276051,0.049542,0.015191,0.129723,0.980394
240,20231228,0.081691,0.174905,0.169516,0.084292,-0.298895,0.305341,0.516293,0.291432,-0.147615,...,0.195393,-0.522331,0.076800,0.539313,0.631646,0.303431,0.092308,0.013131,0.052584,1.090140
241,20231229,0.033257,-0.337262,0.169516,0.478367,-0.296783,0.402419,0.380869,0.275613,-0.123109,...,0.088888,0.641924,0.184108,1.365320,0.613768,0.411084,0.121134,0.009894,0.014461,0.943034

In [80]:
sub_df = df.iloc[:, 1:].apply(zscore, axis=1)
sub_df = pd.DataFrame([pd.Series(array) for array in sub_df])
sub_df

,0,1,2,3,4,5,6,7,8,9,...,5168,5169,5170,5171,5172,5173,5174,5175,5176,5177
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
237,-0.175503,-0.151954,0.047027,-0.246858,-0.598480,0.812276,0.979054,0.126364,-0.533003,-1.274473,...,-0.328065,-0.840363,-0.273262,0.495687,1.039724,0.029393,-0.172378,-0.192802,-0.168977,2.502751
238,-0.217424,-0.159010,0.361733,-0.183092,-0.578563,0.178698,1.098801,0.152782,-0.515557,-1.148569,...,-0.264936,-1.032811,-0.138069,0.493936,0.959838,0.169951,-0.213198,-0.222048,-0.125070,1.580284
239,-0.162509,-0.096595,-0.049564,-0.009088,-0.680926,0.141036,0.534769,0.132188,-0.566827,-1.273885,...,-0.118446,-0.914539,-0.213274,0.455957,0.640235,0.102386,-0.216381,-0.264724,-0.103542,1.093612
240,-0.159085,-0.027314,-0.034933,-0.155408,-0.697092,0.157073,0.455281,0.137411,-0.483238,-1.270373,...,0.001648,-1.012947,-0.165999,0.487823,0.618347,0.154373,-0.144076,-0.256003,-0.200231,1.266486
241,-0.346703,-0.908369,-0.140150,0.328034,-0.847007,0.212905,0.180238,0.020683,-0.583736,0.575089,...,-0.262373,0.575969,-0.118029,1.672557,0.533287,0.226041,-0.213491,-0.382118,-0.375195,1.032419

In [81]:
df.iloc[:, 1:] = sub_df.values
df = df.fillna(0)
df

,date,SH600718,SZ003816,SZ002656,SH688056,SZ000607,SZ001368,SZ003029,SH600651,SH601339,...,SZ301138,SZ301003,SH600936,SZ002497,SH600509,SH600689,SH688108,SZ002034,SZ000680,SH688132
0,20230103,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,20230104,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,20230105,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,20230106,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,20230109,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
237,20231225,-0.175503,-0.151954,0.047027,-0.246858,-0.598480,0.812276,0.979054,0.126364,-0.533003,...,-0.328065,-0.840363,-0.273262,0.495687,1.039724,0.029393,-0.172378,-0.192802,-0.168977,2.502751
238,20231226,-0.217424,-0.159010,0.361733,-0.183092,-0.578563,0.178698,1.098801,0.152782,-0.515557,...,-0.264936,-1.032811,-0.138069,0.493936,0.959838,0.169951,-0.213198,-0.222048,-0.125070,1.580284
239,20231227,-0.162509,-0.096595,-0.049564,-0.009088,-0.680926,0.141036,0.534769,0.132188,-0.566827,...,-0.118446,-0.914539,-0.213274,0.455957,0.640235,0.102386,-0.216381,-0.264724,-0.103542,1.093612
240,20231228,-0.159085,-0.027314,-0.034933,-0.155408,-0.697092,0.157073,0.455281,0.137411,-0.483238,...,0.001648,-1.012947,-0.165999,0.487823,0.618347,0.154373,-0.144076,-0.256003,-0.200231,1.266486
241,20231229,-0.346703,-0.908369,-0.140150,0.328034,-0.847007,0.212905,0.180238,0.020683,-0.583736,...,-0.262373,0.575969,-0.118029,1.672557,0.533287,0.226041,-0.213491,-0.382118,-0.375195,1.032419

In [82]:
print(df.iloc[:,1:].mean(axis=1))
print(df.iloc[:,1:].std(axis=1))

0      0.000000e+00
1      0.000000e+00
2      0.000000e+00
3      0.000000e+00
4      0.000000e+00
           ...
237    5.368865e-17
238    7.032699e-17
239   -2.572939e-19
240   -9.262579e-18
241    7.774563e-17
Length: 242, dtype: float64
0      0.000000
1      0.000000
2      0.000000
3      0.000000
4      0.000000
         ...
237    1.000097
238    1.000097
239    1.000097
240    1.000097
241    1.000097
Length: 242, dtype: float64

In [76]:
df.mean()

date        2.021567e+07
SZ300460   -4.420292e-01
SH603803   -3.155549e-01
SH600536   -4.185548e-01
SH603915   -2.913593e-01
                ...
SZ000520    9.171105e-02
SZ301075   -2.879219e-02
SH688323   -2.506478e-01
SZ002497   -6.205171e-01
SZ002180    1.968663e-01
Length: 5073, dtype: float64

In [69]:
df.iloc[:, 1:].std(axis=0)

SZ300460    0.523506
SH603803    0.678406
SH600536    0.638691
SH603915    0.492434
SZ000009    0.672754
              ...
SZ000520    0.751103
SZ301075    1.428368
SH688323    0.781019
SZ002497    0.722264
SZ002180    0.430914
Length: 5072, dtype: float64

In [83]:
df.to_csv('s_phi_v2_zs_230101_240101_r30.csv', index=False)

In [78]:
df

,date,SZ300460,SH603803,SH600536,SH603915,SZ000009,SZ002557,SH601069,SH600089,SZ300327,...,SH600517,SH688090,SZ002566,SZ002852,SZ301089,SZ000520,SZ301075,SH688323,SZ002497,SZ002180
0,20210104,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,20210105,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,20210106,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,20210107,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,20210108,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
480,20221226,-0.456871,0.535039,-1.719608,-0.651983,0.515295,-0.036554,0.849200,0.447412,-0.433356,...,0.824779,0.464980,-1.692685,0.519380,-1.554981,0.099392,-3.299277,-0.351903,0.261138,0.308987
481,20221227,-0.478827,0.519064,-1.749177,-0.675115,0.499201,0.192962,0.584819,0.430909,-0.455169,...,0.810551,0.448583,-1.722091,0.503310,-1.583557,0.080790,-3.338370,-0.373226,0.243511,0.291649
482,20221228,-0.468239,0.520527,-1.726974,-0.662733,0.466391,0.197407,0.585681,0.433178,-0.444798,...,0.809349,0.450690,-1.700136,0.504917,-2.135985,0.086261,-4.451555,-0.363604,0.247494,0.295192
483,20221229,-0.501051,0.534152,-1.727494,-0.656555,0.479676,0.208998,0.599717,0.446253,-0.437249,...,0.824792,0.463876,-1.700487,0.518445,-2.139080,0.097153,-4.469224,-0.403737,0.259401,0.307399
484,20221230,-0.495154,0.538626,-1.719910,-0.650444,0.484224,0.213919,0.604100,0.450847,-0.431440,...,0.828866,0.468446,-1.692940,0.522939,-2.130930,0.102227,-4.457869,-0.397974,0.264252,0.312184